import './presentation/index.js'
export { deserializeBuildings } from './domain/serialization.js'
export { serializeBuildings } from './domain/serialization.js'
export { resources } from './domain/resources.js'
export { createResourcesVector } from './domain/createResourcesVector.js'
